apiVersion: v1
kind: Service
metadata:
  name: hello-world-nginx-service
  namespace: default
spec:
  type: LoadBalancer
  selector:
    app: hello-world-nginx
  ports:
    - port: 80
      targetPort: 80
